version: '3'

services:
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:9051"]
    volumes:
      - ./api:/app
      - db-data:/db
    ports:
      - "9051:9051"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "9050:9050"

volumes:
  db-data:
  node-modules:
